import fs from 'node:fs/promises';
import path from 'node:path';

import { ensureGitRepository, ensureGitExcludeEntry } from '../core/git.js';
import {
  AGENT_ROLES,
  buildAgentConfig,
  getAgentsRoot,
  getPromptsDir,
  getRepoVsCodeDir,
  getScriptsDir,
  getTicketsDir,
  getWorkspaceDir,
  getRuntimeDir,
  getVsCodeDir
} from '../core/layout.js';

export async function runInit({ targetPath }) {
  await ensureGitRepository(targetPath);

  const agentsRoot = getAgentsRoot(targetPath);
  const directories = [
    agentsRoot,
    getTicketsDir(targetPath),
    getScriptsDir(targetPath),
    getPromptsDir(targetPath),
    getRuntimeDir(targetPath),
    getWorkspaceDir(targetPath),
    getVsCodeDir(targetPath),
    getRepoVsCodeDir(targetPath)
  ];

  await Promise.all(directories.map((directory) => fs.mkdir(directory, { recursive: true })));

  await writeInitFiles(targetPath);
  await ensureGitExcludeEntry(targetPath, '.agents/');

  console.log(`Initialized package-agent workspace in ${agentsRoot}`);
}

async function writeInitFiles(targetPath) {
  const writes = [
    fs.writeFile(
      path.join(getAgentsRoot(targetPath), 'README.md'),
      buildReadme(),
      'utf8'
    ),
    fs.writeFile(
      path.join(getAgentsRoot(targetPath), 'config.json'),
      `${JSON.stringify(buildAgentConfig(), null, 2)}\n`,
      'utf8'
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'start-ticket.sh'),
      buildStartTicketScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'launch-agents.sh'),
      buildLaunchAgentsScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'run-role.sh'),
      buildRunRoleScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'relay.sh'),
      buildRelayScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getWorkspaceDir(targetPath), 'coordinator.md'),
      buildCoordinatorProtocol(),
      'utf8'
    ),
    fs.writeFile(
      path.join(getVsCodeDir(targetPath), 'tasks.sample.json'),
      `${JSON.stringify(buildVsCodeTasks(), null, 2)}\n`,
      'utf8'
    ),
    fs.writeFile(
      path.join(getRepoVsCodeDir(targetPath), 'tasks.json'),
      `${JSON.stringify(buildVsCodeTasks(), null, 2)}\n`,
      'utf8'
    )
  ];

  for (const role of AGENT_ROLES) {
    writes.push(
      fs.writeFile(
        path.join(getPromptsDir(targetPath), `${role}.md`),
        buildAgentPrompt(role),
        'utf8'
      )
    );
  }

  await Promise.all(writes);
}

function buildReadme() {
  return `# .agents workspace

This directory is generated by package-agent and is intended to stay local to the repository.

- \`config.json\` controls provider selection and branch naming.
- \`scripts/start-ticket.sh\` creates a new ticket workspace.
- \`scripts/launch-agents.sh\` prepares the coordinator and agent runtime files.
- \`scripts/relay.sh\` appends a coordinator relay into a role log and transcript.
- \`tickets/<ticket-id>/\` contains per-ticket markdown logs and transcripts.
- \`vscode/tasks.sample.json\` contains a reference task layout.
- \`.vscode/tasks.json\` is where ticket-specific launch tasks are generated.
`;
}

function buildCoordinatorProtocol() {
  return `# Coordinator Protocol

The coordinator is the only role that talks directly to the user.

1. Collect updates from agent logs after each execution cycle.
2. Summarize agent actions, assumptions, and blockers.
3. Ask the user for clarification when any agent cannot proceed.
4. Route the user response back to the relevant agent log.
5. Record every relay event in the ticket transcript.
6. Use \`.agents/scripts/relay.sh <role> <ticket-slug> \"<message>\"\` for manual relays.
`;
}

function buildAgentPrompt(role) {
  return `# ${role}

Role: ${role}

Expected output after each execution:

- Summary of current findings
- Actions completed
- Blockers or questions for the coordinator
- Recommended next step
`;
}

function buildStartTicketScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

ticket_id="\${1-}"

if [[ -z "$ticket_id" ]]; then
  echo "Usage: .agents/scripts/start-ticket.sh <ticket-id>"
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
npx package-agent start-ticket "$ticket_id" --target "$repo_root"
`;
}

function buildLaunchAgentsScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

ticket_id="\${1-}"

if [[ -z "$ticket_id" ]]; then
  echo "Usage: .agents/scripts/launch-agents.sh <ticket-id>"
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
npx package-agent launch-agents "$ticket_id" --target "$repo_root"
`;
}

function buildRunRoleScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

role="\${1-}"
ticket_id="\${2-}"

if [[ -z "$role" || -z "$ticket_id" ]]; then
  echo "Usage: .agents/scripts/run-role.sh <role> <ticket-id>"
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
exec npx package-agent run-role "$role" "$ticket_id" --target "$repo_root"
`;
}

function buildRelayScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

role="\${1-}"
ticket_id="\${2-}"
message="\${3-}"

if [[ -z "$role" || -z "$ticket_id" || -z "$message" ]]; then
  echo "Usage: .agents/scripts/relay.sh <role> <ticket-id> \"<message>\""
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
shift 2
exec npx package-agent relay "$role" "$ticket_id" "$@" --target "$repo_root"
`;
}

function buildVsCodeTasks() {
  return {
    version: '2.0.0',
    tasks: [
      {
        label: 'package-agent:launch:<ticket-slug>',
        type: 'shell',
        command: 'printf "Run this task after package-agent launch-agents <ticket-slug> has generated ticket-specific tasks.\\n"',
        presentation: {
          panel: 'shared'
        },
        problemMatcher: []
      },
      ...['coordinator', ...AGENT_ROLES].map((role) => ({
        label: `package-agent:${role}:<ticket-slug>`,
        type: 'shell',
        command: `.agents/scripts/run-role.sh ${role} <ticket-slug>`,
        options: {
          cwd: '${workspaceFolder}'
        },
        presentation: {
          panel: 'dedicated',
          group: 'package-agent'
        },
        problemMatcher: []
      }))
    ]
  };
}