import fs from 'node:fs/promises';
import path from 'node:path';

import { ensureGitRepository, ensureGitExcludeEntry } from '../core/git.js';
import {
  AGENT_ROLES,
  buildAgentConfig,
  getAgentsRoot,
  getPromptsDir,
  getScriptsDir,
  getTicketsDir,
  getWorkspaceDir,
  getRuntimeDir,
  getVsCodeDir
} from '../core/layout.js';

export async function runInit({ targetPath }) {
  await ensureGitRepository(targetPath);

  const agentsRoot = getAgentsRoot(targetPath);
  const directories = [
    agentsRoot,
    getTicketsDir(targetPath),
    getScriptsDir(targetPath),
    getPromptsDir(targetPath),
    getRuntimeDir(targetPath),
    getWorkspaceDir(targetPath),
    getVsCodeDir(targetPath)
  ];

  await Promise.all(directories.map((directory) => fs.mkdir(directory, { recursive: true })));

  await writeInitFiles(targetPath);
  await ensureGitExcludeEntry(targetPath, '.agents/');

  console.log(`Initialized package-agent workspace in ${agentsRoot}`);
}

async function writeInitFiles(targetPath) {
  const writes = [
    fs.writeFile(
      path.join(getAgentsRoot(targetPath), 'README.md'),
      buildReadme(),
      'utf8'
    ),
    fs.writeFile(
      path.join(getAgentsRoot(targetPath), 'config.json'),
      `${JSON.stringify(buildAgentConfig(), null, 2)}\n`,
      'utf8'
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'start-ticket.sh'),
      buildStartTicketScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getScriptsDir(targetPath), 'launch-agents.sh'),
      buildLaunchAgentsScript(),
      { encoding: 'utf8', mode: 0o755 }
    ),
    fs.writeFile(
      path.join(getWorkspaceDir(targetPath), 'coordinator.md'),
      buildCoordinatorProtocol(),
      'utf8'
    ),
    fs.writeFile(
      path.join(getVsCodeDir(targetPath), 'tasks.sample.json'),
      `${JSON.stringify(buildVsCodeTasks(), null, 2)}\n`,
      'utf8'
    )
  ];

  for (const role of AGENT_ROLES) {
    writes.push(
      fs.writeFile(
        path.join(getPromptsDir(targetPath), `${role}.md`),
        buildAgentPrompt(role),
        'utf8'
      )
    );
  }

  await Promise.all(writes);
}

function buildReadme() {
  return `# .agents workspace

This directory is generated by package-agent and is intended to stay local to the repository.

- \`config.json\` controls provider selection and branch naming.
- \`scripts/start-ticket.sh\` creates a new ticket workspace.
- \`scripts/launch-agents.sh\` prepares the coordinator and agent runtime files.
- \`tickets/<ticket-id>/\` contains per-ticket markdown logs and transcripts.
- \`vscode/tasks.sample.json\` contains a starter multi-terminal VS Code task layout.
`;
}

function buildCoordinatorProtocol() {
  return `# Coordinator Protocol

The coordinator is the only role that talks directly to the user.

1. Collect updates from agent logs after each execution cycle.
2. Summarize agent actions, assumptions, and blockers.
3. Ask the user for clarification when any agent cannot proceed.
4. Route the user response back to the relevant agent log.
5. Record every relay event in the ticket transcript.
`;
}

function buildAgentPrompt(role) {
  return `# ${role}

Role: ${role}

Expected output after each execution:

- Summary of current findings
- Actions completed
- Blockers or questions for the coordinator
- Recommended next step
`;
}

function buildStartTicketScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

ticket_id="\${1-}"

if [[ -z "$ticket_id" ]]; then
  echo "Usage: .agents/scripts/start-ticket.sh <ticket-id>"
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
npx package-agent start-ticket "$ticket_id" --target "$repo_root"
`;
}

function buildLaunchAgentsScript() {
  return `#!/usr/bin/env bash
set -euo pipefail

ticket_id="\${1-}"

if [[ -z "$ticket_id" ]]; then
  echo "Usage: .agents/scripts/launch-agents.sh <ticket-id>"
  exit 1
fi

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
npx package-agent launch-agents "$ticket_id" --target "$repo_root"
`;
}

function buildVsCodeTasks() {
  return {
    version: '2.0.0',
    tasks: AGENT_ROLES.map((role) => ({
      label: `package-agent:${role}`,
      type: 'shell',
      command: `.agents/scripts/launch-agents.sh \${input:ticketId}`,
      options: {
        cwd: '${workspaceFolder}'
      },
      presentation: {
        panel: 'dedicated',
        group: 'package-agent'
      },
      problemMatcher: []
    })),
    inputs: [
      {
        id: 'ticketId',
        type: 'promptString',
        description: 'Ticket identifier'
      }
    ]
  };
}