import fs from 'node:fs/promises';

import {
  AGENT_ROLES,
  ALL_ROLES,
  COORDINATOR_ROLE,
  getRepoTasksPath,
  getRepoVsCodeDir
} from './layout.js';

const GENERATED_DETAIL = 'Generated by package-agent';

export async function writeVsCodeTasks(targetPath, ticketSlug) {
  const tasksPath = getRepoTasksPath(targetPath);
  await fs.mkdir(getRepoVsCodeDir(targetPath), { recursive: true });

  let existingConfig = { version: '2.0.0', tasks: [] };

  try {
    const contents = await fs.readFile(tasksPath, 'utf8');
    const parsed = JSON.parse(contents);

    existingConfig = {
      ...parsed,
      tasks: Array.isArray(parsed.tasks) ? parsed.tasks : []
    };
  } catch (error) {
    if (error.code !== 'ENOENT') {
      throw new Error(`Could not parse ${tasksPath}. Fix the JSON before package-agent can manage VS Code tasks.`);
    }
  }

  const preservedTasks = existingConfig.tasks.filter(
    (task) => task.detail !== GENERATED_DETAIL && !(typeof task.label === 'string' && task.label.startsWith('package-agent:'))
  );

  const nextConfig = {
    version: existingConfig.version || '2.0.0',
    ...copyTopLevelFields(existingConfig),
    tasks: [...preservedTasks, ...buildTasks(ticketSlug)]
  };

  await fs.writeFile(tasksPath, `${JSON.stringify(nextConfig, null, 2)}\n`, 'utf8');

  return tasksPath;
}

function copyTopLevelFields(existingConfig) {
  const next = {};

  for (const [key, value] of Object.entries(existingConfig)) {
    if (key === 'version' || key === 'tasks') {
      continue;
    }

    next[key] = value;
  }

  return next;
}

function buildTasks(ticketSlug) {
  const prepareLabel = buildPrepareLabel(ticketSlug);
  const spawnLabel = buildSpawnLabel(ticketSlug);
  const roleLabels = ALL_ROLES.map((role) => buildRoleLabel(role, ticketSlug));

  return [
    {
      label: buildLaunchLabel(ticketSlug),
      detail: GENERATED_DETAIL,
      dependsOrder: 'sequence',
      dependsOn: [prepareLabel, spawnLabel],
      type: 'shell',
      command: `printf 'package-agent launch ready for ${ticketSlug}\\n'`,
      presentation: {
        reveal: 'always',
        panel: 'shared'
      },
      problemMatcher: []
    },
    {
      label: prepareLabel,
      detail: GENERATED_DETAIL,
      type: 'shell',
      command: `npx package-agent launch-agents ${ticketSlug} --target \"\${workspaceFolder}\" --skip-vscode-tasks`,
      options: {
        cwd: '${workspaceFolder}'
      },
      presentation: {
        reveal: 'always',
        panel: 'dedicated',
        group: 'package-agent-prepare'
      },
      problemMatcher: []
    },
    {
      label: spawnLabel,
      detail: GENERATED_DETAIL,
      dependsOrder: 'parallel',
      dependsOn: roleLabels,
      type: 'shell',
      command: `printf 'package-agent agent terminals streaming for ${ticketSlug}\\n'`,
      presentation: {
        reveal: 'never',
        panel: 'shared'
      },
      problemMatcher: []
    },
    ...buildRoleTasks(ticketSlug)
  ];
}

function buildRoleTasks(ticketSlug) {
  return ALL_ROLES.map((role) => ({
    label: buildRoleLabel(role, ticketSlug),
    detail: GENERATED_DETAIL,
    type: 'shell',
    command: `.agents/scripts/run-role.sh ${role} ${ticketSlug}`,
    options: {
      cwd: '${workspaceFolder}'
    },
    presentation: {
      reveal: 'always',
      focus: role === COORDINATOR_ROLE,
      panel: 'dedicated',
      group: `package-agent-${ticketSlug}`,
      clear: true,
      showReuseMessage: false
    },
    problemMatcher: []
  }));
}

function buildLaunchLabel(ticketSlug) {
  return `package-agent:launch:${ticketSlug}`;
}

function buildPrepareLabel(ticketSlug) {
  return `package-agent:prepare:${ticketSlug}`;
}

function buildSpawnLabel(ticketSlug) {
  return `package-agent:spawn:${ticketSlug}`;
}

function buildRoleLabel(role, ticketSlug) {
  return `package-agent:${role}:${ticketSlug}`;
}

export function buildLaunchInstructions(ticketSlug) {
  return {
    task: buildLaunchLabel(ticketSlug),
    roles: [COORDINATOR_ROLE, ...AGENT_ROLES].map((role) => buildRoleLabel(role, ticketSlug)),
    relayCommands: AGENT_ROLES.map((role) => ({
      role,
      command: `.agents/scripts/relay.sh ${role} ${ticketSlug} \"<message>\"`
    }))
  };
}